language: java
jdk:
  - openjdk7
  - oraclejdk7
before_script:
  - mysql -e 'create database hibernate_search;'
script:
- mvn test
- mvn test -Pfunctional-test -Dselenium.driver=firefox
env: MAVEN_OPTS="-XX:MaxPermSize=128m"
addons:
  firefox: "22.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"